version: '3.7'

networks:
  front-tier:
  back-tier:

services:
  
    cadvisor:
      image: google/cadvisor
      restart: always
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      ports:
        - 8080:8080
      networks:
        - back-tier
